name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Configure and build
      uses: threeal/cmake-action@main
      with:
        source-dir: .
        build-dir: build
    - name: Create TeX file
      run: |
        mkdir out
        build/language > out/ipa.tex
        cp data/*.tex out/
